### ISSUE TITLE
тупой скат

### ISSUE THREAD

**Issue by IngeniousA** [IngeniousA/ImCurrAE#1]
123

**Comment by DmitryTech** [comment]
in 4 : 2, 3, 4, 6

**Comment by IngeniousA** [comment]
in 3
модальный диалог -- виджет, где юзеру нужно выбрать вариант ответа. модальный диалог замораживает другие виджеты, пока он не закроется.

**Comment by DmitryTech** [comment]
ffffffffffffffffffffffff

**Comment by Sliffki** [comment]
ну шо, ребят, погнали нахой

**Comment by IngeniousA** [comment]
# F

**Comment by Sliffki** [comment]
press F to pay respect

**Comment by Sliffki** [comment]
есть что-нибудь?

**Comment by DmitryTech** [comment]
в 1 один
в 5 (пустая таблица) возможно!!! 145507

**Comment by Sliffki** [comment]
в 1 не один

**Comment by Sliffki** [comment]
один во 2

**Comment by Sliffki** [comment]
это в файле "0" написано, что это ответы со второго номер
